-- =====================================================================
-- FINCA·HaTA CX 대시보드 1단계 DB 설정
-- Supabase > SQL Editor 에 전체를 붙여넣고 Run 하세요. (여러 번 실행해도 안전)
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. 기준 코드 (VOC 구분, 사유 카테고리, 플랫폼 등) - 기준 관리 메뉴에서 수정
-- ---------------------------------------------------------------------
create table if not exists code_items (
  id bigint generated by default as identity primary key,
  group_key text not null,
  label text not null,
  sort_order int not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (group_key, label)
);

insert into code_items (group_key, label, sort_order) values
  ('brand', '핀카', 1), ('brand', '하타', 2),

  ('platform', '29CM', 1), ('platform', '자사몰', 2), ('platform', '무신사', 3),
  ('platform', 'W컨셉', 4), ('platform', 'EQL', 5), ('platform', '기타', 9),

  ('handler', '진이슬', 1), ('handler', '장진아', 2), ('handler', '김성희', 3),

  ('voc_type', '(반품)브랜드과실', 1), ('voc_type', '(교환)브랜드과실', 2),
  ('voc_type', '재입고 문의', 3), ('voc_type', '상품 문의', 4),
  ('voc_type', '배송 문의/지연', 5), ('voc_type', '오배송/누락', 6),
  ('voc_type', '강성 고객', 7), ('voc_type', '기타', 9),

  ('consult_method', '교환반품접수', 1), ('consult_method', '게시판', 2),
  ('consult_method', '1:1 채팅', 3), ('consult_method', '리뷰', 4),
  ('consult_method', '전화', 5), ('consult_method', '기타', 9),

  ('status', '접수', 1), ('status', '확인중', 2), ('status', '처리완료', 3), ('status', '보상완료', 4),

  -- 사유 카테고리: 기존 시트의 중복 항목을 합친 통합안
  ('reason', '파손/구멍/올나감', 1), ('reason', '이염/오염/물빠짐', 2),
  ('reason', '박음질불량', 3), ('reason', '프린팅불량', 4),
  ('reason', '부자재 불량(지퍼·단추·스냅)', 5), ('reason', '바코드/매칭 오류', 6),
  ('reason', '디자인/색상 차이', 7), ('reason', '사이즈/핏', 8),
  ('reason', '오배송/누락', 9), ('reason', '기타', 99),

  -- 액션 보드에 표시되는 후속 조치
  ('action', '상품개선', 1), ('action', '리오더', 2),
  ('action', '재고 검수', 3), ('action', '상세페이지 수정', 4)
on conflict (group_key, label) do nothing;

-- ---------------------------------------------------------------------
-- 2. VOC 접수 (기존 'VOC 접수 대장' 시트)
-- ---------------------------------------------------------------------
create table if not exists voc_cases (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  received_date date not null default current_date,
  brand text not null,
  handler text,
  platform text,
  order_no text,
  orderer text,
  receiver text,
  product_id bigint references products(id),
  product_name text,
  voc_type text,
  consult_method text,
  status text not null default '접수',
  reason_category text,
  reason_detail text,
  note text,
  action_required text,
  action_done boolean not null default false,
  photos text[] not null default '{}'
);

create index if not exists voc_cases_received_date_idx on voc_cases (received_date);
create index if not exists voc_cases_product_id_idx on voc_cases (product_id);

-- ---------------------------------------------------------------------
-- 3. CX 응대 주의사항
-- ---------------------------------------------------------------------
create table if not exists cx_guides (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

insert into cx_guides (title, body, sort_order)
select '플랫폼 게시판 상담',
  E'자사몰 및 외부 채널 유도 답변 시 대량 벌점이 부과되어 패널티(2주간 전 상품 판매금지 등)를 받습니다.\n'
  || E'- 판매링크뿐 아니라 언급, 1:1 채팅 등 모든 외부 언급 금지\n'
  || E'- 29CM / 무신사가 가장 주의가 필요하며, 타 플랫폼도 언급하지 않는 것을 원칙으로 합니다.\n\n'
  || E'[금지 예시]\n'
  || E'- (자사몰 or 타 플랫폼 링크) 해당 링크에서 구매가 가능합니다.\n'
  || E'- 29CM은 품절이며 자사몰 or 타 플랫폼에서 판매중입니다.\n'
  || E'- 자세한 상담을 위해 해피톡으로 문의주세요.\n'
  || E'- (해피톡 링크) 여기로 문의주시면 자세히 안내 드리겠습니다.',
  1
where not exists (select 1 from cx_guides);

-- ---------------------------------------------------------------------
-- 4. 로그인한 직원만 읽기/쓰기 가능하도록 보안 설정
-- ---------------------------------------------------------------------
alter table code_items enable row level security;
alter table voc_cases enable row level security;
alter table cx_guides enable row level security;

drop policy if exists "staff all" on code_items;
drop policy if exists "staff all" on voc_cases;
drop policy if exists "staff all" on cx_guides;
create policy "staff all" on code_items for all to authenticated using (true) with check (true);
create policy "staff all" on voc_cases for all to authenticated using (true) with check (true);
create policy "staff all" on cx_guides for all to authenticated using (true) with check (true);

-- ---------------------------------------------------------------------
-- 5. VOC 사진 저장소 (비공개, 로그인한 직원만 접근)
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('voc-photos', 'voc-photos', false)
on conflict (id) do nothing;

drop policy if exists "staff read voc photos" on storage.objects;
drop policy if exists "staff upload voc photos" on storage.objects;
drop policy if exists "staff delete voc photos" on storage.objects;
create policy "staff read voc photos" on storage.objects for select to authenticated using (bucket_id = 'voc-photos');
create policy "staff upload voc photos" on storage.objects for insert to authenticated with check (bucket_id = 'voc-photos');
create policy "staff delete voc photos" on storage.objects for delete to authenticated using (bucket_id = 'voc-photos');
