-- =====================================================================
-- FINCA·HaTA CX 대시보드 - CS 데일리 DB 설정
-- Supabase > SQL Editor 에 전체를 붙여넣고 Run 하세요. (여러 번 실행해도 안전)
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. CS 데일리 (기존 '데일리' 시트)
--    날짜(보고일, 전일 접수 기준) · 브랜드 · 플랫폼별 한 줄
--    platform = '브랜드 전체' 줄에는 해피톡·전화 건수만 입력
-- ---------------------------------------------------------------------
create table if not exists cs_daily (
  id bigint generated by default as identity primary key,
  report_date date not null,
  brand text not null,
  platform text not null,
  orders int not null default 0,
  cancels int not null default 0,
  return_simple int not null default 0,
  return_defect int not null default 0,
  return_misship int not null default 0,
  return_etc int not null default 0,
  exchange_simple int not null default 0,
  exchange_defect int not null default 0,
  exchange_misship int not null default 0,
  exchange_etc int not null default 0,
  reviews_total int not null default 0,
  reviews_negative int not null default 0,
  reviews_positive int not null default 0,
  board_total int not null default 0,
  ht_total int not null default 0,
  ht_only int not null default 0,
  ht_delivery int not null default 0,
  ht_return int not null default 0,
  ht_cancel int not null default 0,
  ht_product int not null default 0,
  ht_etc int not null default 0,
  ht_voc int not null default 0,
  call_in int not null default 0,
  call_delivery int not null default 0,
  call_return int not null default 0,
  call_cancel int not null default 0,
  call_product int not null default 0,
  call_etc int not null default 0,
  call_out int not null default 0,
  updated_at timestamptz not null default now(),
  unique (report_date, brand, platform)
);

-- ---------------------------------------------------------------------
-- 2. 월간 보고 메모 (기존 '월간 리뷰' 시트의 VOC·주요 이슈 직접 입력 칸)
-- ---------------------------------------------------------------------
create table if not exists report_notes (
  id bigint generated by default as identity primary key,
  month text not null,          -- 'YYYY-MM'
  brand text not null,
  voc_memo text,
  issue_memo text,
  updated_at timestamptz not null default now(),
  unique (month, brand)
);

-- ---------------------------------------------------------------------
-- 3. 데일리 입력용 브랜드별 플랫폼 (기준 관리 메뉴에서 수정)
-- ---------------------------------------------------------------------
insert into code_items (group_key, label, sort_order) values
  ('daily_platform:핀카', '29CM', 1), ('daily_platform:핀카', '아임웹', 2), ('daily_platform:핀카', '무신사', 3),
  ('daily_platform:하타', '29CM', 1), ('daily_platform:하타', '아임웹', 2), ('daily_platform:하타', '무신사', 3),
  ('daily_platform:하타', 'W컨셉', 4), ('daily_platform:하타', 'EQL', 5)
on conflict (group_key, label) do nothing;

-- ---------------------------------------------------------------------
-- 4. 로그인한 직원만 접근
-- ---------------------------------------------------------------------
alter table cs_daily enable row level security;
alter table report_notes enable row level security;
drop policy if exists "staff all" on cs_daily;
drop policy if exists "staff all" on report_notes;
create policy "staff all" on cs_daily for all to authenticated using (true) with check (true);
create policy "staff all" on report_notes for all to authenticated using (true) with check (true);
