-- =====================================================================
-- FINCA·HaTA CX 대시보드 - 리뷰 · 게시판 DB 설정
-- Supabase > SQL Editor 에 전체를 붙여넣고 Run 하세요. (여러 번 실행해도 안전)
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. 리뷰 (플랫폼 리뷰 다운로드 파일을 업로드)
--    source_key = 작성시각 + 내용으로 만든 값 → 같은 리뷰를 다시 올려도 중복 안 됨
-- ---------------------------------------------------------------------
create table if not exists review_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  brand text not null,
  platform text not null,
  source_key text not null,
  product_name text,
  product_id bigint references products(id),
  option_text text,
  rating int,
  content text,
  written_at timestamptz,
  order_no text,
  note text,                 -- 부정 리뷰 처리 내용
  handled boolean not null default false,
  unique (platform, source_key)
);
create index if not exists review_items_written_at_idx on review_items (written_at);

-- ---------------------------------------------------------------------
-- 2. 게시판 문의 (플랫폼 게시판 다운로드 파일을 업로드)
-- ---------------------------------------------------------------------
create table if not exists board_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  brand text not null,
  platform text not null,
  source_key text not null,
  product_name text,
  product_id bigint references products(id),
  option_text text,
  platform_category text,    -- 플랫폼이 붙인 문의 구분 (무신사 등)
  title text,
  content text,
  written_at timestamptz,
  answer text,
  answered_at timestamptz,
  inquiry_type text,         -- 대시보드가 분류한 유형 (재입고, 배송 ...)
  note text,
  unique (platform, source_key)
);
create index if not exists board_items_written_at_idx on board_items (written_at);

-- ---------------------------------------------------------------------
-- 3. 로그인한 직원만 접근
-- ---------------------------------------------------------------------
alter table review_items enable row level security;
alter table board_items enable row level security;
drop policy if exists "staff all" on review_items;
drop policy if exists "staff all" on board_items;
create policy "staff all" on review_items for all to authenticated using (true) with check (true);
create policy "staff all" on board_items for all to authenticated using (true) with check (true);
