-- =====================================================================
-- FINCA·HaTA CX 대시보드 - 업무 매뉴얼 게시판 DB 설정
-- Supabase > SQL Editor 에 전체를 붙여넣고 Run 하세요. (여러 번 실행해도 안전)
-- =====================================================================

create table if not exists manuals (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  category text,
  title text not null,
  body text,
  pinned boolean not null default false,
  attachments jsonb not null default '[]',   -- [{ path, name, type }]
  author text
);

alter table manuals enable row level security;
drop policy if exists "staff all" on manuals;
create policy "staff all" on manuals for all to authenticated using (true) with check (true);

-- 첨부파일 저장소 (비공개, 로그인한 직원만)
insert into storage.buckets (id, name, public)
values ('manual-files', 'manual-files', false)
on conflict (id) do nothing;

drop policy if exists "staff read manual files" on storage.objects;
drop policy if exists "staff upload manual files" on storage.objects;
drop policy if exists "staff delete manual files" on storage.objects;
create policy "staff read manual files" on storage.objects for select to authenticated using (bucket_id = 'manual-files');
create policy "staff upload manual files" on storage.objects for insert to authenticated with check (bucket_id = 'manual-files');
create policy "staff delete manual files" on storage.objects for delete to authenticated using (bucket_id = 'manual-files');
