-- =====================================================================
-- FINCA·HaTA CX 대시보드 - 주문(판매) 데이터
-- Supabase > SQL Editor 에 전체를 붙여넣고 Run 하세요. (여러 번 실행해도 안전)
-- 고객 정보(주문자·수령자·연락처·주소)는 저장하지 않음
-- =====================================================================

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  brand text not null,
  platform text not null,
  source_key text not null,        -- 플랫폼 주문 품목 번호 (중복 업로드 방지)
  order_no text,
  status text,                     -- 주문상태 (배송완료, 취소 등)
  claim_status text,               -- 클레임 상태 (무신사)
  product_name text,
  option_text text,
  qty int not null default 1,
  ordered_at timestamptz,
  order_date date,
  category text,                   -- 자동 분류: 베딩·러그·바스·홈데코·웨어·잡화·키친
  is_set boolean not null default false,
  cancel_reason text,              -- 취소사유 (아임웹)
  return_reason text,              -- 반품사유 (아임웹)
  unique (platform, source_key)
);
create index if not exists order_items_order_date_idx on order_items (order_date);

alter table order_items enable row level security;
drop policy if exists "staff all" on order_items;
create policy "staff all" on order_items for all to authenticated using (true) with check (true);
