-- =====================================================================
-- FINCA·HaTA CX 대시보드 - 예약배송 관리
-- Supabase > SQL Editor 에 전체를 붙여넣고 Run 하세요. (여러 번 실행해도 안전)
-- 고객 정보는 주문자 이름만 저장 (연락처·주소는 저장하지 않음)
-- =====================================================================

-- 예약상품 일정 (예약상품리스트)
create table if not exists preorder_products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  code text not null unique,        -- 단품코드 (오클릭 바코드와 같음)
  product_name text,
  option_text text,
  first_in date,                    -- 최초 입고예정
  first_out date,                   -- 최초 출고일 공지
  change1_notice date,              -- 1차 일정 변경 공지일
  change1_in date,                  -- 1차 변경 입고일
  change1_out date,                 -- 1차 변경 출고안내일
  change2_notice date,
  change2_in date,
  change2_out date,
  actual_in date,                   -- 실제입고일
  note text,
  status text not null default '진행'   -- 진행 / 종료
);

-- 예약 주문 품목 (오클릭 미출고 파일을 올릴 때마다 갱신) + 지연 안내 기록
create table if not exists preorder_lines (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  line_key text not null unique,    -- 주문번호|바코드|사이즈
  order_no text not null,           -- 오클릭 주문번호
  seller text,                      -- 판매처
  seller_order_no text,             -- 판매처주문번호
  input_date date,                  -- 입력일
  purchase_date date,               -- 구매일 (판매처주문번호의 날짜, 없으면 입력일)
  orderer text,                     -- 주문자 이름 (안내용)
  barcode text,
  product_name text,
  size text,
  qty int,
  stock int,
  avail int,                        -- 가용재고
  unshipped int,                    -- 미출고
  first_seen date,                  -- 처음 올라온 날
  last_seen date,                   -- 마지막으로 올라온 날
  status text not null default '출고대기',   -- 출고대기 / 출고완 / 취소
  shipped_on date,
  split text,                       -- 합배송 / 분리배송 (주문 단위)
  notice1_method text,              -- 유선 / 문자
  notice1_date date,
  notice2_method text,
  notice2_date date,
  gift text,
  memo text
);
create index if not exists preorder_lines_order_idx on preorder_lines (order_no);
create index if not exists preorder_lines_status_idx on preorder_lines (status);

-- 업로드 기록 (출고완 처리 내역 확인·되돌리기용)
create table if not exists preorder_uploads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  snapshot_date date not null,
  file_name text,
  line_count int,
  order_count int,
  new_count int,
  shipped_orders text[],            -- 이번에 출고완 처리된 주문번호
  note text
);

alter table preorder_products enable row level security;
alter table preorder_lines enable row level security;
alter table preorder_uploads enable row level security;
drop policy if exists "staff all" on preorder_products;
drop policy if exists "staff all" on preorder_lines;
drop policy if exists "staff all" on preorder_uploads;
create policy "staff all" on preorder_products for all to authenticated using (true) with check (true);
create policy "staff all" on preorder_lines for all to authenticated using (true) with check (true);
create policy "staff all" on preorder_uploads for all to authenticated using (true) with check (true);
