-- =====================================================================
-- FINCA·HaTA CX 대시보드 - CX 미팅 로그 (노션 회의록을 옮겨옴)
-- Supabase > SQL Editor 에 전체를 붙여넣고 Run 하세요. (여러 번 실행해도 안전)
-- =====================================================================

create table if not exists meetings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  meeting_date date not null,
  title text not null,
  kind text not null default 'CX 회의',     -- CX 회의 / PJ 회의
  attendees text,
  status text not null default '진행중',    -- 진행중 / 완료
  body text,                                -- 회의 내용 (마크다운)
  notion_url text unique                    -- 노션에서 가져온 회의록 (중복 가져오기 방지)
);
create index if not exists meetings_date_idx on meetings (meeting_date);

-- 논의사항: 완료될 때까지 다음 회의에 자동으로 따라감
create table if not exists meeting_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  meeting_id bigint not null references meetings(id) on delete cascade,
  title text not null,
  detail text,
  owner text,
  status text not null default '진행중',    -- 진행중 / 완료
  done_at date,
  sort int not null default 0
);
create index if not exists meeting_items_meeting_idx on meeting_items (meeting_id);

alter table meetings enable row level security;
alter table meeting_items enable row level security;
drop policy if exists "staff all" on meetings;
drop policy if exists "staff all" on meeting_items;
create policy "staff all" on meetings for all to authenticated using (true) with check (true);
create policy "staff all" on meeting_items for all to authenticated using (true) with check (true);
