-- =====================================================================
-- FINCA·HaTA CX 대시보드 - 업무 보드 (직원끼리 할 일 요청·체크)
-- Supabase > SQL Editor 에 전체를 붙여넣고 Run 하세요. (여러 번 실행해도 안전)
-- =====================================================================

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  body text,
  requester text,                          -- 요청한 사람
  assignee text,                           -- 담당자
  due_date date,                           -- 마감일
  status text not null default '할 일',     -- 할 일 / 진행중 / 완료
  done_at date,
  priority text not null default '보통'     -- 급함 / 보통
);
create index if not exists tasks_status_idx on tasks (status);

create table if not exists task_comments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  task_id bigint not null references tasks(id) on delete cascade,
  author text,
  body text not null
);
create index if not exists task_comments_task_idx on task_comments (task_id);

alter table tasks enable row level security;
alter table task_comments enable row level security;
drop policy if exists "staff all" on tasks;
drop policy if exists "staff all" on task_comments;
create policy "staff all" on tasks for all to authenticated using (true) with check (true);
create policy "staff all" on task_comments for all to authenticated using (true) with check (true);
