-- =====================================================================
-- FINCA·HaTA CX 대시보드 - 주문 월별·상품별 요약 (상반기 등 지난 주문을 가볍게 저장)
-- Supabase > SQL Editor 에 전체를 붙여넣고 Run 하세요. (여러 번 실행해도 안전)
-- 주문을 한 줄씩 저장하지 않고 월·브랜드·판매처·상품별 개수만 저장 (용량 약 1/20)
-- =====================================================================

create table if not exists order_monthly (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ym text not null,                -- 2026-03
  brand text not null,
  platform text not null,
  product_name text not null,
  category text,                   -- 자동 분류: 베딩·러그·바스·홈데코·웨어·잡화·키친
  is_set boolean not null default false,
  lines int not null default 0,    -- 주문 품목 줄 수 (취소 포함)
  qty int not null default 0,      -- 수량 합
  cancels int not null default 0,  -- 주문상태에 '취소'
  returns int not null default 0,  -- 주문·클레임 상태에 '반품'
  exchanges int not null default 0,-- 주문·클레임 상태에 '교환'
  unique (ym, brand, platform, product_name)
);
create index if not exists order_monthly_ym_idx on order_monthly (ym);

alter table order_monthly enable row level security;
drop policy if exists "staff all" on order_monthly;
create policy "staff all" on order_monthly for all to authenticated using (true) with check (true);
