-- =====================================================================
-- FINCA·HaTA CX 대시보드 - 반품·교환 (한 건씩, 상품·사유별 분석용)
-- Supabase > SQL Editor 에 전체를 붙여넣고 Run 하세요. (여러 번 실행해도 안전)
-- 고객 정보(이름·연락처·주소)는 저장하지 않음
-- =====================================================================

create table if not exists return_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  brand text not null,
  platform text not null,
  source_key text not null,        -- 중복 업로드 방지용 (판매처 + 주문·품목 번호 등)
  kind text not null,              -- 반품 / 교환
  order_no text,
  product_name text,
  option_text text,
  qty int not null default 1,
  reason_raw text,                 -- 판매처 사유 그대로 (예: 상품파손/상품불량, 구매 의사 취소)
  reason_detail text,              -- 고객이 적은 상세 사유
  reason_group text,               -- 묶은 사유: 단순변심·사이즈/옵션·불량/파손·오배송/누락·배송·상품불만족/정보상이·기타
  is_fault boolean not null default false,   -- 브랜드 과실 (불량/파손·오배송/누락)
  claim_status text,               -- 판매처 처리 상태 (반품 완료 등)
  order_date date,                 -- 주문일
  claim_date date,                 -- 반품·교환 요청(접수)일, 없으면 비움
  category text,                   -- 자동 분류: 베딩·러그·바스·홈데코·웨어·잡화·키친
  unique (platform, source_key)
);
create index if not exists return_items_order_date_idx on return_items (order_date);

alter table return_items enable row level security;
drop policy if exists "staff all" on return_items;
create policy "staff all" on return_items for all to authenticated using (true) with check (true);
