-- =====================================================================
-- FINCA·HaTA CX 대시보드 - 팀 캘린더 (휴가·외근·미팅 등 우리 팀끼리 공유)
-- Supabase > SQL Editor 에 전체를 붙여넣고 Run 하세요. (여러 번 실행해도 안전)
-- =====================================================================

create table if not exists team_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  kind text not null default '미팅',        -- 휴가 / 반차 / 외근 / 미팅 / 교육 / 행사 / 기타
  title text not null,
  person text,                              -- 누구 일정인지 (처리자 이름, 비우면 팀 전체)
  start_date date not null,
  end_date date not null,                   -- 하루짜리는 start_date와 같음
  start_time text,                          -- '14:00' (없으면 하루 종일)
  memo text,
  author text
);
create index if not exists team_events_date_idx on team_events (start_date, end_date);

alter table team_events enable row level security;
drop policy if exists "staff all" on team_events;
create policy "staff all" on team_events for all to authenticated using (true) with check (true);
